### ISSUE TITLE
Any requirements on the input HTML?

### ISSUE THREAD

**Issue by Balatonia** [erichround/LREC_IGT#2]
Hi,

I'm trying to apply the grammar harvester to a descriptive grammar - an HTML version of Mansfields book on Murrinhpatha.
When I run the script, it detects the _body_. file and the _params_ file, but throws the following error:
==== murrinhpatha_body_ ====
2021-10-01 11:26:05 HTML_to_XML_conversion
Error in read_xml.raw(charToRaw(enc2utf8(x)), "UTF-8", ..., as_html = as_html,  : 
  error parsing attribute name [68]

Are there are requirements that my input HTML does not obey? 

Best,
Luise

**Comment by erichround** [comment]
Hi Luise,

Thanks for the question.  The premise of our code is that the process starts with a scan of a paper document, rather than a modern HTML file.  So, when the code is processing HTML, the HTML it expects is a file exported from the commercial pdf-reading software Abbyy Reader.  Mansfield's book would be a born-digital file, so unfortunately not the kind of thing our code would work on.

Best wishes,
Erich

[This paper](https://www.aclweb.org/anthology/2020.lrec-1.351.pdf ) gives a quick explanation of what the code was attempting. It's much more a proof-of-concept than user-friend tool, I'm afraid.
